"""Estado inicial sincronizado

Revision ID: 237784ebb950
Revises: 
Create Date: 2026-01-09 05:19:16.549892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237784ebb950'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coach_certificacion')
    with op.batch_alter_table('arcos', schema=None) as batch_op:
        batch_op.alter_column('arco_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('idx_arcos_miembro'))

    with op.batch_alter_table('atletas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_atletas_clase'))

    with op.batch_alter_table('clases', schema=None) as batch_op:
        batch_op.alter_column('clase_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('idx_clases_coach'))

    with op.batch_alter_table('miembros', schema=None) as batch_op:
        batch_op.alter_column('miembro_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('idx_miembros_correo'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miembros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_miembros_correo'), ['correo'], unique=False)
        batch_op.alter_column('miembro_id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('clases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_clases_coach'), ['coach_id'], unique=False)
        batch_op.alter_column('clase_id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('atletas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_atletas_clase'), ['clase_id'], unique=False)

    with op.batch_alter_table('arcos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_arcos_miembro'), ['miembro_id'], unique=False)
        batch_op.alter_column('arco_id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    op.create_table('coach_certificacion',
    sa.Column('miembro_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('certificacion', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('fecha_obtencion', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['miembro_id'], ['coachs.miembro_id'], name=op.f('fk_coach_cert_coach'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('miembro_id', 'certificacion', name=op.f('pk_coach_cert'))
    )
    # ### end Alembic commands ###
