-- ==========================================================
-- PRACTICA 5 — MODELO OLTP: Club de Tiro con Arco IPN
-- PostgreSQL 15+
-- Tablas: miembros, coachs, clases, atletas, arcos, coach_certificacion
-- Restricciones: PK, FK, UNIQUE, NOT NULL, CHECK, DEFAULT + índices
-- ISA: total y solapada (miembro debe ser coach o atleta, o ambos)
-- ==========================================================

-- Limpieza re-ejecutable
DROP TRIGGER  IF EXISTS trg_enforce_miembro_has_role ON miembros;
DROP FUNCTION IF EXISTS enforce_miembro_has_role();

DROP TABLE IF EXISTS coach_certificacion CASCADE;
DROP TABLE IF EXISTS atletas            CASCADE;
DROP TABLE IF EXISTS clases             CASCADE;
DROP TABLE IF EXISTS arcos              CASCADE;
DROP TABLE IF EXISTS miembros           CASCADE;

-- ======================
--  Tabla: miembros
-- ======================
CREATE TABLE miembros (
  miembro_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  curp        VARCHAR(18)  NOT NULL UNIQUE,
  correo      VARCHAR(120),
  celular     VARCHAR(20),
  edad        SMALLINT,
  alergias    TEXT,
  fecha_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT ck_miembros_curp_formato
    CHECK (curp ~ '^[A-Z]{4}[0-9]{6}[HM][A-Z]{5}[0-9A-Z][0-9]$'),
  CONSTRAINT ck_miembros_edad_rango
    CHECK (edad IS NULL OR edad BETWEEN 8 AND 90),
  CONSTRAINT ck_miembros_correo_formato
    CHECK (correo IS NULL OR correo ~ '^[^@]+@[^@]+\.[^@]+$'),
  CONSTRAINT ck_miembros_celular_mx
    CHECK (celular IS NULL OR celular ~ '^[0-9]{10}$')
);

-- ======================
--  Tabla: coachs (subtipo ISA)
-- ======================
CREATE TABLE coachs (
  miembro_id  INTEGER PRIMARY KEY
);

-- ======================
--  Tabla: clases
-- ======================
CREATE TABLE clases (
  clase_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dias         VARCHAR(40),
  hora_inicio  TIME NOT NULL,
  hora_fin     TIME NOT NULL,
  nivel        VARCHAR(30) NOT NULL DEFAULT 'Inicial',
  coach_id     INTEGER NOT NULL,

  CONSTRAINT ck_clases_horario
    CHECK (hora_fin > hora_inicio),
  CONSTRAINT ck_clases_nivel
    CHECK (nivel IN ('Inicial','Intermedio','Avanzado'))
);

-- ======================
--  Tabla: atletas (subtipo ISA)
--  Regla negocio: atleta pertenece a UNA clase (clase_id NOT NULL)
-- ======================
CREATE TABLE atletas (
  miembro_id  INTEGER      PRIMARY KEY,
  boleta      VARCHAR(20)  UNIQUE,
  alumno_ipn  BOOLEAN      NOT NULL DEFAULT FALSE,
  nivel       VARCHAR(30)  NOT NULL DEFAULT 'Inicial',
  clase_id    INTEGER      NOT NULL,

  CONSTRAINT ck_atletas_nivel
    CHECK (nivel IN ('Inicial','Intermedio','Avanzado')),
  CONSTRAINT ck_atletas_boleta_formato
    CHECK (boleta IS NULL OR boleta ~ '^[0-9]{8,12}$'),
  CONSTRAINT ck_atletas_boleta_obligatoria_si_ipn
    CHECK (NOT alumno_ipn OR boleta IS NOT NULL)
);

-- ======================
--  Tabla: arcos (1:N con miembros)
-- ======================
CREATE TABLE arcos (
  arco_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo          VARCHAR(30)  NOT NULL DEFAULT 'recurvo',
  librAje       SMALLINT     NOT NULL,
  mano          VARCHAR(10)  NOT NULL DEFAULT 'diestro',
  estabilizador BOOLEAN      NOT NULL DEFAULT FALSE,
  mira          BOOLEAN      NOT NULL DEFAULT FALSE,
  rama          VARCHAR(40),
  maneral       VARCHAR(40),
  miembro_id    INTEGER      NOT NULL,

  CONSTRAINT ck_arcos_tipo
    CHECK (tipo IN ('recurvo','compuesto','barebow','tradicional')),
  CONSTRAINT ck_arcos_libraje
    CHECK (librAje BETWEEN 10 AND 70),
  CONSTRAINT ck_arcos_mano
    CHECK (mano IN ('diestro','zurdo'))
);

-- ======================
--  Tabla: coach_certificacion (multivaluado de coach)
-- ======================
CREATE TABLE coach_certificacion (
  miembro_id     INTEGER      NOT NULL,
  certificacion  VARCHAR(120) NOT NULL,
  fecha_obtencion DATE NOT NULL DEFAULT CURRENT_DATE,
  CONSTRAINT pk_coach_cert PRIMARY KEY (miembro_id, certificacion)
);

-- ======================
--  FKs + acciones referenciales
-- ======================
ALTER TABLE coachs
  ADD CONSTRAINT fk_coachs_miembro
  FOREIGN KEY (miembro_id)
  REFERENCES miembros(miembro_id)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE clases
  ADD CONSTRAINT fk_clases_coach
  FOREIGN KEY (coach_id)
  REFERENCES coachs(miembro_id)
  ON DELETE RESTRICT
  ON UPDATE CASCADE;

ALTER TABLE atletas
  ADD CONSTRAINT fk_atletas_miembro
  FOREIGN KEY (miembro_id)
  REFERENCES miembros(miembro_id)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE atletas
  ADD CONSTRAINT fk_atletas_clase
  FOREIGN KEY (clase_id)
  REFERENCES clases(clase_id)
  ON DELETE RESTRICT
  ON UPDATE CASCADE;

ALTER TABLE arcos
  ADD CONSTRAINT fk_arcos_miembro
  FOREIGN KEY (miembro_id)
  REFERENCES miembros(miembro_id)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE coach_certificacion
  ADD CONSTRAINT fk_coach_cert_coach
  FOREIGN KEY (miembro_id)
  REFERENCES coachs(miembro_id)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

-- ======================
--  Índices recomendados
-- ======================
CREATE INDEX IF NOT EXISTS idx_clases_coach    ON clases(coach_id);
CREATE INDEX IF NOT EXISTS idx_atletas_clase   ON atletas(clase_id);
CREATE INDEX IF NOT EXISTS idx_arcos_miembro   ON arcos(miembro_id);
CREATE INDEX IF NOT EXISTS idx_miembros_correo ON miembros(correo);

-- ======================
--  ISA TOTAL SOLAPADA: cada miembro debe ser atleta o coach (o ambos)
--  Trigger DEFERRABLE: valida al COMMIT
-- ======================
CREATE OR REPLACE FUNCTION enforce_miembro_has_role()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM miembros m
    WHERE NOT EXISTS (SELECT 1 FROM atletas a WHERE a.miembro_id = m.miembro_id)
      AND NOT EXISTS (SELECT 1 FROM coachs  c WHERE c.miembro_id = m.miembro_id)
  ) THEN
    RAISE EXCEPTION 'Existe al menos un miembro sin rol (ISA total violada).';
  END IF;
  RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER trg_enforce_miembro_has_role
AFTER INSERT OR UPDATE OR DELETE ON miembros
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION enforce_miembro_has_role();
